spawn ssh -o StrictHostKeyChecking=no root@37.60.251.4 export KUBECONFIG=/etc/rancher/k3s/k3s.yaml; kubectl get configmap -n ess ess-matrix-authentication-service-patched -o yaml
root@37.60.251.4's password: 
apiVersion: v1
data:
  config.yaml: "# Matrix Authentication Service Configuration\n# Patched: 2026-01-07
    21:57:29\n\n# OAuth клиенты\nclients:\n  - client_id: 0000000000000000000SYNAPSE\n
    \   client_auth_method: client_secret_basic\n    client_secret: SynapseSuperSecret\n\n#
    Upstream issuer\nupstream:\n  issuer: https://auth.gigglin.tech/\n\n# HTTP listeners\nhttp:\n
    \ listeners:\n    - name: web\n      resources:\n        - name: discovery\n        -
    name: human\n        - name: oauth\n        - name: compat\n        - name: graphql\n
    \         playground: true\n        - name: assets\n      binds:\n        - address:
    \"[::]:8080\"\n\n# Email настройки (Yandex SMTP)\nemail:\n  from: \" <>\"\n  reply_to:
    \"\"\n  transport: smtp\n  hostname: \n  port: \n  mode: starttls\n  username:
    \n  password: \n\n# Matrix homeserver\nmatrix:\n  homeserver: matrix.gigglin.tech\n
    \ endpoint: http://ess-synapse.ess.svc.cluster.local:8008\n  secret: SynapseSuperSecret\n\n#
    Password схемы\npasswords:\n  enabled: true\n  schemes:\n    - version: 1\n      algorithm:
    argon2id\n\n# ВКЛЮЧАЕМ РЕГИСТРАЦИЮ\naccount:\n  registration:\n    enabled: true\n
    \   require_email_verification: true\n    \n# Database\ndatabase:\n  uri: env://MAS_DATABASE_URL\n\n#
    Secrets (будут загружены из environment)\nsecrets:\n  encryption: env://MAS_ENCRYPTION_KEY\n
    \ keys:\n    - kid: primary\n      key: env://MAS_SIGNING_KEY\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"# Matrix Authentication Service Configuration\n# Patched: 2026-01-07 21:57:29\n\n# OAuth клиенты\nclients:\n  - client_id: 0000000000000000000SYNAPSE\n    client_auth_method: client_secret_basic\n    client_secret: SynapseSuperSecret\n\n# Upstream issuer\nupstream:\n  issuer: https://auth.gigglin.tech/\n\n# HTTP listeners\nhttp:\n  listeners:\n    - name: web\n      resources:\n        - name: discovery\n        - name: human\n        - name: oauth\n        - name: compat\n        - name: graphql\n          playground: true\n        - name: assets\n      binds:\n        - address: \"[::]:8080\"\n\n# Email настройки (Yandex SMTP)\nemail:\n  from: \" \u003c\u003e\"\n  reply_to: \"\"\n  transport: smtp\n  hostname: \n  port: \n  mode: starttls\n  username: \n  password: \n\n# Matrix homeserver\nmatrix:\n  homeserver: matrix.gigglin.tech\n  endpoint: http://ess-synapse.ess.svc.cluster.local:8008\n  secret: SynapseSuperSecret\n\n# Password схемы\npasswords:\n  enabled: true\n  schemes:\n    - version: 1\n      algorithm: argon2id\n\n# ВКЛЮЧАЕМ РЕГИСТРАЦИЮ\naccount:\n  registration:\n    enabled: true\n    require_email_verification: true\n    \n# Database\ndatabase:\n  uri: env://MAS_DATABASE_URL\n\n# Secrets (будут загружены из environment)\nsecrets:\n  encryption: env://MAS_ENCRYPTION_KEY\n  keys:\n    - kid: primary\n      key: env://MAS_SIGNING_KEY\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"ess-matrix-authentication-service-patched","namespace":"ess"}}
  creationTimestamp: "2026-01-07T20:57:29Z"
  name: ess-matrix-authentication-service-patched
  namespace: ess
  resourceVersion: "8047"
  uid: 1ec3522a-85e0-4b7b-8e83-bfb8a5c9d443
Tanquzsacjev5hywvo
